#!/usr/bin/env bash

uname=$(expr substr $(uname -s) 1 5)

echo "Installing starship.rs (🚀 blazing fast)"
if [ $uname == "MINGW" ]; then
    powershell 'winget install --id Starship.Starship'
else
    curl -sS https://starship.rs/install.sh | sh -s -- --yes
fi

echo "Copying .bashrc to user directory"
cp files/.bashrc $HOME

echo "Copying .gitconfig to user directory"
cp files/.gitconfig $HOME