#!/usr/bin/env bash

uname=$(expr substr $(uname -s) 1 5)
bin="/usr/local/bin"

if [ $uname == "MINGW" ]; then
    bin="$HOME/.local/bin"
fi

mkdir -p $bin

echo "Installing starship.rs (🚀 blazing fast)"
curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir $bin

if [ $uname == "MINGW" ]; then
    echo "Copying .bashrc to user directory"
    cp files/.bashrc $HOME
    
    echo "Copying .gitconfig to user directory"
    cp files/.gitconfig $HOME
else
    echo "Creating symlink for .bashrc"
    ls -s files/.bashrc $HOME/.bashrc
    
    echo "Creating symlink for .gitconfig"
    ls -s files/.gitconfig $HOME/.gitconfig
fi