#!/usr/bin/env bash

uname=$(expr substr $(uname -s) 1 5)


if [ $uname == "MINGW" ]; then
    echo "Installing starship.rs (🚀 blazing fast)"
    powershell 'winget install --id Starship.Starship'
    echo "Copying .bashrc to user directory"
    cp files/.bashrc $HOME
    
    echo "Copying .gitconfig to user directory"
    cp files/.gitconfig $HOME

    exit 0
fi

echo "Installing starship.rs (🚀 blazing fast)"
curl -sS https://starship.rs/install.sh | sh -s -- --yes

echo "Symlinking .bashrc to user directory"
ln -sf "$PWD/files/.bashrc" $HOME

echo "Symlinking .gitconfig to user directory"
ln -sf "$PWD/files/.gitconfig" $HOME

read -p "Are you going to use i3 on this installation? (y/N) " i3;
i3=${i3:-n}
if [ $i3 == "y" ] || [ $i3 == "Y" ]; then
        echo "Symlinking i3 directories"
        ln -sf "$PWD/files/config/i3" $HOME/.config/i3
        ln -sf "$PWD/files/config/i3blocks" $HOME/.config/i3blocks
fi
