#!/usr/bin/env bash

echo "Are you sure you want to shut down your computer? (y/N)"

read answer

if [ "$answer" == "y" ] || [ "$answer" == "Y" ] || [ "$answer" == "yes" ]
then
    systemctl poweroff
fi