#!/usr/bin/env bash

echo "Are you sure you want to put your computer to sleep? (y/N)"

read answer

if [ "$answer" == "y" ] || [ "$answer" == "Y" ] || [ "$answer" == "yes" ]
then
    systemctl suspend
fi